docs: update minutes of first three weeks of coding period.
fossology/gsoc pull request #156
Opened 2023-06-19 16:41 UTC by k-avy

## Project

License as a service 

### Changes

Added the report and minutes of first three weeks of coding period.

2023-06-20 06:14 UTC, avinal requested changes
Please use Grammarly/LanguageTool extension to fix grammatical errors. Also format your markdown files.

2023-06-20 06:14 UTC, avinal commented on docs/2023/laas/updates/2023-06-02.md
> +author url: https://github.com/k-avy
```suggestion
author_url: https://github.com/k-avy
```
Interesting that build did not fail.

2023-06-20 06:14 UTC, avinal commented on docs/2023/laas/updates/2023-06-02.md
> +
You have to add a licensing text to all the markdown files as well. Please see other's PR.

2023-06-20 06:14 UTC, avinal commented on docs/2023/laas/updates/2023-06-09.md
> +author url: https://github.com/k-avy
```suggestion
author_url: https://github.com/k-avy
```

2023-06-20 06:14 UTC, avinal commented on docs/2023/laas/updates/2023-06-09.md
> +
Add licensing text

2023-06-20 06:14 UTC, avinal commented on docs/2023/laas/updates/2023-06-09.md
> +* Do we want plane log or structured log:
```suggestion
* Do we want plain log or structured log?
```

2023-06-20 06:14 UTC, avinal commented on docs/2023/laas/updates/2023-06-09.md
> +* Marydone is feild for candidate license flag.
```suggestion
* Marydone is field for candidate license flag.
```

2023-06-22 13:33 UTC, GMishx requested changes

2023-06-22 13:33 UTC, GMishx commented on docs/2023/laas/updates/2023-06-16.md
> +* SPDX id will aso be a required feild in create.
```suggestion
* SPDX id will also be a required field in create.
```

2023-06-22 13:33 UTC, GMishx commented on docs/2023/laas/updates/2023-06-16.md
> +## COnclusion and future plan
```suggestion
## Conclusion and future plan
```

2023-06-23 02:22 UTC, GMishx approved these changes

2023-06-23 02:22 UTC, merged