chore(report) : Add community bonding report
fossology/gsoc pull request #211
Opened 2024-06-05 09:26 UTC by rajuljha

## Project

Community Bonding report for @rajuljha for GSoC' 24

### Changes

Add community bonding report and add personal as well as project details.

2024-06-06 00:26 UTC, GMishx requested changes

2024-06-06 00:26 UTC, GMishx commented on docs/2024/ci-scanner/updates/2023-05-30.md
Please rename the file to report's date.

2024-06-06 04:55 UTC, rajuljha commented on docs/2024/ci-scanner/updates/2023-05-30.md
Done!

2024-06-06 09:42 UTC, avinal requested changes
Slight change, rest looks good to me.

2024-06-06 09:42 UTC, avinal commented on docs/2024/ci-scanner/index.md
> +dependencies
Please simplify this. Either write it in bullet points or separate the paragraphs. Try active voice.

2024-06-06 09:42 UTC, avinal commented on docs/2024/ci-scanner/updates/2024-05-07.md
Okay for community bonding, but for next updates, please try to include more from the discussion, like a few lines about the solution that was discussed/accepted.

2024-06-06 13:09 UTC, rajuljha commented on docs/2024/ci-scanner/updates/2024-05-07.md
I have updated the project info as well as provided more meaningful community bonding report.

2024-06-06 13:45 UTC, avinal approved these changes
Looks good to me

2024-06-07 07:42 UTC, GMishx commented
@rajuljha please update the commit message "Update report date" according to the contributing guidelines.

Hint: you can modify the message when you do interactive rebase.

2024-06-07 08:28 UTC, rajuljha commented
> @rajuljha please update the commit message "Update report date" according to the contributing guidelines.
> 
> Hint: you can modify the message when you do interactive rebase.

Thanks for the tip! Please take a look if it is fine now?

2024-06-07 08:43 UTC, GMishx approved these changes

2024-06-07 08:43 UTC, merged