chore(report): REST APIs week 3 report
fossology/gsoc pull request #221
Opened 2024-06-21 14:48 UTC by dvjsharma

## Project

GSoC'24 week 2 report for REST API Improvements @dvjsharma

2024-06-27 07:52 UTC, GMishx requested changes

2024-06-27 07:52 UTC, GMishx commented on docs/2024/rest/updates/2024-06-11.md
Dear @dvjsharma with recent changes in #216 the directory structure for the project has changed. Kindly rebase the branch with latest changes.

2024-06-27 13:55 UTC, dvjsharma commented on docs/2024/rest/updates/2024-06-11.md
Fixed some bugs from #216 and did the rebase, PTAL.

2024-07-04 10:18 UTC, GMishx approved these changes

2024-07-04 10:18 UTC, merged