fix(readme) update directory structure to avoid confusion of week-05 meeting notes.
fossology/gsoc pull request #261
Opened 2024-07-17 06:17 UTC by Aaditya-Singh78

## Project

Scheduler Overhaul

### Changes

+ update the directory structure for organising `06th June` & `07th June` meeting notes.

### Notes
Please review the updates for accuracy and completeness. If there are any adjustments needed, let me know or feel free to suggest edits directly on the PR.

cc: @shaheemazmalmmd , @GMishx

2024-07-17 12:09 UTC, GMishx requested changes
@Aaditya-Singh78 please rebase the branch to avoid additional merge commit

2024-07-23 07:47 UTC, GMishx approved these changes

2024-07-23 07:49 UTC, GMishx commented
@Aaditya-Singh78 please rebase to resolve merge conflicts.

2025-06-12 20:51 UTC, shaheemazmalmmd commented
Closing this branch as there is no response from creator since last year.

2025-06-12 20:51 UTC, closed without merging