docs(ReactUI): Updates for meeting 1
fossology/gsoc pull request #51
Opened 2022-06-05 15:47 UTC by krishna9304

## Project

React UI

### Changes

Community Bonding Meeting 1 updates added.

2022-06-05 17:05 UTC, GMishx requested changes

2022-06-05 17:05 UTC, GMishx commented on docs/2022/ui/updates/krishna/2022-06-02.md
>  SPDX-FileCopyrightText: 2022 Krishna Mahato <@gmail.com>
Please fix the email in copyright.

2022-06-05 17:05 UTC, GMishx commented on docs/2022/ui/index.md
> -
Please revert unnecessary changes.

2022-06-05 17:05 UTC, GMishx commented on docs/2022/ui/index.md
> +
Please revert unnecessary changes.

2022-06-05 19:04 UTC, krishna9304 commented on docs/2022/ui/updates/krishna/2022-06-02.md
>  SPDX-FileCopyrightText: 2022 Krishna Mahato <@gmail.com>
Done!

2022-06-05 19:04 UTC, krishna9304 commented on docs/2022/ui/index.md
> -
Sure, Done.

2022-06-07 07:50 UTC, GMishx approved these changes

2022-06-07 07:52 UTC, merged