added 2022-06-09 weekly meeting details
fossology/gsoc pull request #58
Opened 2022-06-14 06:25 UTC by Ayush7614

Signed-off-by: Ayush Kumar [ayushknj3@gmail.com](mailto:ayushknj3@@gmail.com)

## Project

ReactUI

### Changes

Added 9 June Meeting update

2022-06-14 09:56 UTC, GMishx requested changes

2022-06-14 09:56 UTC, GMishx commented on docs/2022/ui/updates/ayush/2022-06-09.md
> +- My Sem end exams are going on then after i start contribution
```suggestion
- My Sem end exams are going on, after which I start to contribution.
```

2022-06-17 17:16 UTC, Ayush7614 commented on docs/2022/ui/updates/ayush/2022-06-09.md
> +- My Sem end exams are going on then after i start contribution
Done @GMishx

2022-06-17 17:30 UTC, Ayush7614 commented
migrate all weekly meeting code and details in one file

2022-06-21 07:24 UTC, GMishx commented on docs/2022/ui/updates/ayush/2022-06-02.md
> +*(June 16th, 2022)*
Hello @Ayush7614 ,
As from June 13, the coding period started, so please move updates to a new weekly file under same folder as done in previous run:
https://github.com/fossology/gsoc/tree/main/docs/2021/copyrights/updates

2022-06-28 11:16 UTC, GMishx commented on docs/2022/ui/updates/ayush/2022-06-02.md
> +*(June 16th, 2022)*
Any updates on this @Ayush7614 ?

2022-07-02 12:56 UTC, GMishx commented
Can we close the PR @Ayush7614 if there are no updates from you?

2022-07-02 13:09 UTC, Ayush7614 commented
No @GMishx wait for today i am update all the reports and added all the meeting discussion in my next PRs and also correct this PR

2022-07-13 13:28 UTC, GMishx commented
Closing the PR as there are no updates.

Please reopen if needed.

2022-07-13 13:28 UTC, closed without merging